import { Equipment, MaintenanceType } from './types';

export const SECTORS = [
  "Produção",
  "Vestiário",
  "Área Fria",
  "Área Externa",
  "Embalagem",
  "Sala de Descongelamento",
  "Sala de Manipulação",
  "Expedição",
  "Serra",
  "Extrusão",
  "Moinho",
  "Caldeira",
  "E.T.E",
  "Refeitório",
  "Administração",
  "Manutenção",
  "Qualidade, gerência e PCP",
  "Fulão",
  "Estufa",
  "Câmara",
  "Barracão",
  "Computadores",
  "RH",
  "Comercial"
];

export const MAINTENANCE_TYPES = [
  MaintenanceType.CORRECTIVE,
  MaintenanceType.PREVENTIVE,
  MaintenanceType.PREDICTIVE
];

const SECTOR_MAPPING: Record<string, string> = {
  "produção": "Produção",
  "vestiário": "Vestiário",
  "vestiário masculino": "Vestiário",
  "vestiário feminino": "Vestiário",
  "área fria": "Área Fria",
  "area fria": "Área Fria",
  "área externa": "Área Externa",
  "area externa": "Área Externa",
  "embalagem": "Embalagem",
  "sala de descongelamento": "Sala de Descongelamento",
  "sala de manipulação": "Sala de Manipulação",
  "manipulação": "Sala de Manipulação",
  "expedição": "Expedição",
  "serra": "Serra",
  "extrusão": "Extrusão",
  "moinho": "Moinho",
  "caldeira": "Caldeira",
  "e.t.e": "E.T.E",
  "ete": "E.T.E",
  "refeitório": "Refeitório",
  "administração": "Administração",
  "manutenção": "Manutenção",
  "qualidade, gerência e pcp": "Qualidade, gerência e PCP",
  "pcp": "Qualidade, gerência e PCP",
  "estufa": "Estufa",
  "câmara": "Câmara",
  "barracão": "Barracão",
  "computadores": "Computadores",
  "computadores rh": "Computadores",
  "computadores - rh": "Computadores",
  "computadores - comercial": "Computadores",
  "computadores - adm": "Computadores",
  "computadores - pcp": "Computadores",
  "computadores - embalagem": "Computadores",
  "computadores - expedição": "Computadores",
  "computadores - extrusão": "Computadores",
  "rh": "RH",
  "comercial": "Comercial",
  "antecâmara": "Área Fria",
  "barreira sanitária úmida": "Área Fria",
  "barreira sanitária seca": "Área Fria",
  "barreira área seca": "Área Fria",
  "corredor dos carrinhos": "Produção",
  "corredor de carrinhos": "Produção",
  "corredor estufa": "Estufa",
  "corredor estufas 1-4": "Estufa",
  "sala pcp": "Qualidade, gerência e PCP",
  "insumo": "Produção",
  "dml": "Produção",
  "sala dalton": "Produção",
  "patio da empresa": "Área Externa",
  "patio": "Área Externa",
  "higienização": "Produção",
  "sala de higienização": "Produção",
  "estoque de bobinas": "Produção",
  "embalagem primária": "Embalagem",
  "embalagem secundária": "Embalagem",
  "sala de reunião": "Administração",
  "sala diretoria": "Administração",
  "sistema de cloração": "Manutenção",
  "banco de capacitores": "Manutenção",
  "moldadora de bifinho": "Produção",
  "elaine": "Produção",
  "fabrica": "Produção",
  "filial": "Área Externa",
  "lavabotas área fr": "Área Fria",
  "serra fita - embalagem": "Serra",
  "área seca": "Área Fria"
};

export const normalizeSector = (sector: string): string => {
  if (!sector) return SECTORS[0];
  const normalized = sector.toLowerCase().trim();
  return SECTOR_MAPPING[normalized] || SECTORS[0];
};

export const MOCK_ASSETS_CSV: Equipment[] = [
  { tag: "1", name: "Vestiário Masculino", sector: "Vestiário" },
  { tag: "2", name: "VESTIÁRIO FEMININO", sector: "Vestiário" },
  { tag: "3", name: "Chapa da doca", sector: "Área Fria" },
  { tag: "4", name: "Pátio", sector: "Área Externa" },
  { tag: "6", name: "Gerador de espuma", sector: "Área Fria" },
  { tag: "6", name: "Caldeira", sector: "Área Externa" },
  { tag: "6", name: "Máquina de costura 3", sector: "Embalagem" },
  { tag: "7", name: "Suporte mangueira", sector: "Área Fria" },
  { tag: "8", name: "Refeitório", sector: "Área Externa" },
  { tag: "9", name: "Sala de Descongelamento", sector: "Sala de Descongelamento" },
  { tag: "10", name: "Ventilador", sector: "Área Fria" },
  { tag: "11", name: "Escritório", sector: "Administração" },
  { tag: "12", name: "ÁREA FRIA", sector: "Área Fria" },
  { tag: "13", name: "Buffet térmico", sector: "Refeitório" },
  { tag: "14", name: "Sala de manipulação", sector: "Sala de Manipulação" },
  { tag: "15", name: "Forro", sector: "Produção" },
  { tag: "16", name: "Escada moinho", sector: "Moinho" },
  { tag: "17", name: "Paleteira inox", sector: "Área Fria" },
  { tag: "18", name: "Setor de Expedição", sector: "Expedição" },
  { tag: "19", name: "corredor das estufas area fria", sector: "Área Fria" },
  { tag: "20", name: "Carrinho", sector: "Produção" },
  { tag: "21", name: "Seladora automática 4", sector: "Embalagem" },
  { tag: "22", name: "area externa", sector: "Área Externa" },
  { tag: "23", name: "Rack", sector: "Qualidade, gerência e PCP" },
  { tag: "24", name: "Prateleiras", sector: "Produção" },
  { tag: "25", name: "SETOR DA EMBALAGEM", sector: "Embalagem" },
  { tag: "26", name: "Faca", sector: "Sala de Manipulação" },
  { tag: "27", name: "Refletor", sector: "Extrusão" },
  { tag: "28", name: "Mesa", sector: "Produção" },
  { tag: "29", name: "carrinho de glicerina manipulação", sector: "Sala de Manipulação" },
  { tag: "30", name: "VENTILADOR 60CM", sector: "Área Fria" },
  { tag: "31", name: "Suporte de glicerina", sector: "Sala de Manipulação" },
  { tag: "31", name: "Higienização", sector: "Produção" },
  { tag: "32", name: "Extintor", sector: "Área Fria" },
  { tag: "33", name: "Paleteira", sector: "Área Fria" },
  { tag: "34", name: "Carrinho", sector: "Extrusão" },
  { tag: "35", name: "Cadeira", sector: "Produção" },
  { tag: "36", name: "Paleteira azul", sector: "Serra" },
  { tag: "37", name: "Seladora Cetro", sector: "Embalagem"},
  { tag: "38", name: "Prateleiras", sector: "Produção" },
  { tag: "39", name: "Lâmpada led tubular", sector: "Estufa" },
  { tag: "40", name: "Rack", sector: "Embalagem" },
  { tag: "41", name: "Carrinho de glicerina", sector: "Extrusão" },
  { tag: "42", name: "Ventilador", sector: "Área Fria" },
  { tag: "43", name: "Suporte de proteção do painel", sector: "Estufa" },
  { tag: "44", name: "Paleteira", sector: "Área Fria" },
  { tag: "45", name: "Paleteira", sector: "Área Fria" },
  { tag: "46", name: "Setor da Extrusão", sector: "Extrusão" },
  { tag: "47", name: "Chave para abrir galão", sector: "Extrusão" },
  { tag: "48", name: "Biodigestor", sector: "Área Externa" },
  { tag: "49", name: "Mangueira - sala descongelamentos", sector: "Sala de Descongelamento" },
  { tag: "50", name: "Stand Up Pounch", sector: "Embalagem" },
  { tag: "51", name: "Ventilador", sector: "Área Fria" },
  { tag: "52", name: "Relógio ponto", sector: "Área Fria" },
  { tag: "53", name: "Armadilha luminosa", sector: "Área Fria" },
  { tag: "54", name: "Balança de chão 1000kg", sector: "Área Fria" },
  { tag: "55", name: "Tanque de polipropileno 1-3", sector: "Sala de Descongelamento" },
  { tag: "56", name: "Tanque de polipropileno 4-6", sector: "Sala de Descongelamento" },
  { tag: "57", name: "Tanque de polipropileno 7-9", sector: "Sala de Descongelamento" },
  { tag: "58", name: "Mesa para inverter tripa", sector: "Sala de Descongelamento" },
  { tag: "59", name: "Motobomba periférica - mesa inverter tripa", sector: "Sala de Descongelamento" },
  { tag: "60", name: "Caixa inox - mesa inverter tripa", sector: "Sala de Descongelamento" },
  { tag: "61", name: "Tanque tingimento tripa", sector: "Sala de Descongelamento" },
  { tag: "61", name: "Suporte em inox para as bandejas", sector: "Área Fria" },
  { tag: "62", name: "Paleteira", sector: "Sala de Descongelamento" },
  { tag: "63", name: "Câmara fria 1", sector: "Câmara" },
  { tag: "64", name: "Painel de comando", sector: "Câmara" },
  { tag: "65", name: "Compressor", sector: "Câmara" },
  { tag: "66", name: "Evaporador", sector: "Câmara" },
  { tag: "67", name: "Câmara fria 2", sector: "Câmara" },
  { tag: "68", name: "Painel de comando 1", sector: "Câmara" },
  { tag: "69", name: "Painel de comando 2", sector: "Câmara" },
  { tag: "70", name: "Compressor 1", sector: "Câmara" },
  { tag: "71", name: "Compressor 2", sector: "Câmara" },
  { tag: "72", name: "Evaporador 1 c/ 5 motores", sector: "Câmara" },
  { tag: "73", name: "Evaporador 2 c/ 5 motores", sector: "Câmara" },
  { tag: "74", name: "Balança de chão 1000kg", sector: "Sala de Manipulação" },
  { tag: "75", name: "Balança 50kg", sector: "Sala de Manipulação" },
  { tag: "76", name: "Balança 50kg", sector: "Sala de Manipulação" },
  { tag: "77", name: "Mesa inox 1", sector: "Sala de Manipulação" },
  { tag: "78", name: "Mesa inox 2", sector: "Sala de Manipulação" },
  { tag: "79", name: "Mesa inox 3", sector: "Sala de Manipulação" },
  { tag: "79", name: "Argola em inox", sector: "Área Fria" },
  { tag: "80", name: "Mesa inox 4", sector: "Sala de Manipulação" },
  { tag: "81", name: "Bifetadeira", sector: "Sala de Manipulação" },
  { tag: "82", name: "Ventilador 1", sector: "Sala de Manipulação" },
  { tag: "83", name: "Ventilador 2", sector: "Sala de Manipulação" },
  { tag: "84", name: "Ventilador 3", sector: "Sala de Manipulação" },
  { tag: "85", name: "Motobomba periférica de água", sector: "Sala de Manipulação" },
  { tag: "86", name: "CLIMATIZADOR ECO BRISA", sector: "Sala de Manipulação" },
  { tag: "87", name: "Hidrolavadora", sector: "Produção" },
  { tag: "88", name: "Exaustor", sector: "Produção" },
  { tag: "89", name: "Misturador de vapor", sector: "Produção" },
  { tag: "90", name: "Ar condicionado", sector: "Qualidade, gerência e PCP" },
  { tag: "91", name: "Gaveteiro inox 1", sector: "Qualidade, gerência e PCP" },
  { tag: "92", name: "Gaveteiro inox 2", sector: "Qualidade, gerência e PCP" },
  { tag: "92", name: "Porta", sector: "Área Fria" },
  { tag: "93", name: "Ventilador", sector: "Expedição" },
  { tag: "94", name: "Armário inox 2", sector: "Qualidade, gerência e PCP" },
  { tag: "95", name: "Armário inox 3", sector: "Qualidade, gerência e PCP" },
  { tag: "96", name: "Armário inox 4", sector: "Qualidade, gerência e PCP" },
  { tag: "97", name: "Armário inox 5", sector: "Qualidade, gerência e PCP" },
  { tag: "98", name: "Datadora", sector: "Qualidade, gerência e PCP" },
  { tag: "99", name: "Analisador de umidade", sector: "Qualidade, gerência e PCP" },
  { tag: "99", name: "Chão", sector: "Produção" },
  { tag: "100", name: "Analisador de aw 1", sector: "Qualidade, gerência e PCP" },
  { tag: "101", name: "Analisador de aw 2", sector: "Qualidade, gerência e PCP" },
  { tag: "101", name: "Dispenser sabonete", sector: "Área Fria" },
  { tag: "102", name: "ESTUFA 05", sector: "Sala de Manipulação" },
  { tag: "103", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "104", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "104", name: "Sala PCP", sector: "Qualidade, gerência e PCP" },
  { tag: "105", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "106", name: "ESTUFA 06", sector: "Sala de Manipulação" },
  { tag: "107", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "108", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "109", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "110", name: "ESTUFA 07", sector: "Sala de Manipulação" },
  { tag: "111", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "112", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "113", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "114", name: "Motor elétrico 4", sector: "Estufa" },
  { tag: "115", name: "ESTUFA 08", sector: "Sala de Manipulação" },
  { tag: "116", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "117", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "118", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "119", name: "Motor elétrico 4", sector: "Estufa" },
  { tag: "120", name: "Quadro de comando 5-6", sector: "Estufa" },
  { tag: "121", name: "Quadro de comando 7", sector: "Área Fria" },
  { tag: "122", name: "Quadro de comando 8", sector: "Estufa" },
  { tag: "123", name: "Armadilha luminosa", sector: "Estufa" },
  { tag: "124", name: "Bebedouro", sector: "Estufa" },
  { tag: "125", name: "Extrusora 1", sector: "Extrusão" },
  { tag: "126", name: "Motor alimentador extrusora", sector: "Extrusão" },
  { tag: "127", name: "Redutor alimentador extrusora", sector: "Extrusão" },
  { tag: "128", name: "Extrusora 2", sector: "Extrusão" },
  { tag: "129", name: "Motor alimentador extrusora", sector: "Extrusão" },
  { tag: "130", name: "Redutor alimentador extrusora", sector: "Extrusão" },
  { tag: "131", name: "Motor extrusora", sector: "Extrusão" },
  { tag: "132", name: "Redutor extrusora", sector: "Extrusão" },
  { tag: "133", name: "Masseira inox 1", sector: "Extrusão" },
  { tag: "134", name: "Masseira inox 2", sector: "Extrusão" },
  { tag: "135", name: "Motor", sector: "Extrusão" },
  { tag: "136", name: "Redutor motor", sector: "Extrusão" },
  { tag: "137", name: "Torre de resfriamento", sector: "Extrusão" },
  { tag: "138", name: "Motor torre resfriamento", sector: "Extrusão" },
  { tag: "139", name: "Ventilador 1", sector: "Extrusão" },
  { tag: "140", name: "Ventilador 2", sector: "Extrusão" },
  { tag: "141", name: "Ventilador 3", sector: "Extrusão" },
  { tag: "142", name: "Ventilador 4", sector: "Extrusão" },
  { tag: "143", name: "Mesa", sector: "Extrusão" },
  { tag: "144", name: "Balança 15kg", sector: "Extrusão" },
  { tag: "145", name: "Painel de controle alimentador extrusora", sector: "Extrusão" },
  { tag: "147", name: "Painel de controle da masseira", sector: "Extrusão" },
  { tag: "148", name: "Painel de controle água quente", sector: "Extrusão" },
  { tag: "149", name: "Paleteira", sector: "Produção" },
  { tag: "150", name: "Armadilha luminosa", sector: "Extrusão" },
  { tag: "151", name: "Ventilador", sector: "Extrusão" },
  { tag: "152", name: "Estufa 1", sector: "Estufa" },
  { tag: "152", name: "ESTUFA 01", sector: "Área Fria" },
  { tag: "153", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "154", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "155", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "156", name: "Motor elétrico 4", sector: "Estufa" },
  { tag: "157", name: "Motor elétrico 5", sector: "Estufa" },
  { tag: "158", name: "Estufa 2", sector: "Estufa" },
  { tag: "158", name: "ESTUFA 02", sector: "Área Fria" },
  { tag: "159", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "160", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "161", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "162", name: "Estufa 3", sector: "Estufa" },
  { tag: "162", name: "ESTUFA 02", sector: "Área Fria" },
  { tag: "163", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "164", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "165", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "166", name: "ESTUFA 04", sector: "Área Fria" },
  { tag: "167", name: "Motor elétrico 1", sector: "Estufa" },
  { tag: "168", name: "Motor elétrico 2", sector: "Estufa" },
  { tag: "169", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "170", name: "Quadro de comando 1-2", sector: "Estufa" },
  { tag: "171", name: "Quadro de comando 3-4", sector: "Estufa" },
  { tag: "172", name: "Armadilha luminosa", sector: "Estufa" },
  { tag: "173", name: "Paleteira", sector: "Estufa" },
  { tag: "174", name: "SERRA FITA", sector: "Serra" },
  { tag: "175", name: "SERRA FITA", sector: "Serra" },
  { tag: "176", name: "SERRA FITA", sector: "Serra" },
  { tag: "177", name: "Balança 50kg", sector: "Serra" },
  { tag: "178", name: "Balança 50kg", sector: "Serra" },
  { tag: "180", name: "CLIMATIZADOR ECO BRISA", sector: "Serra" },
  { tag: "181", name: "Ventilador", sector: "Serra" },
  { tag: "182", name: "Máquina de costura 2", sector: "Embalagem" },
  { tag: "183", name: "CLIMATIZADOR ECO BRISA", sector: "Embalagem" },
  { tag: "184", name: "Flowpack 1", sector: "Embalagem" },
  { tag: "185", name: "Flowpack 2", sector: "Embalagem" },
  { tag: "186", name: "Túnel de encolhimento", sector: "Embalagem" },
  { tag: "187", name: "Seladora semi automática 1", sector: "Embalagem" },
  { tag: "188", name: "Seladora semi automática 2", sector: "Embalagem" },
  { tag: "189", name: "Detector de metais", sector: "Embalagem" },
  { tag: "190", name: "Motor detector de metais", sector: "Embalagem" },
  { tag: "191", name: "Impressora", sector: "Embalagem" },
  { tag: "192", name: "Fechadora de caixa 1", sector: "Embalagem" },
  { tag: "193", name: "Fechadora de caixa 2", sector: "Embalagem" },
  { tag: "194", name: "Fechadora de caixa 3", sector: "Embalagem" },
  { tag: "195", name: "SELADORA CETRO", sector: "Embalagem" },
  { tag: "196", name: "Seladora registron", sector: "Embalagem" },
  { tag: "197", name: "SELADORA CETRO", sector: "Embalagem" },
  { tag: "198", name: "SELADORA EM L", sector: "Embalagem" },
  { tag: "199", name: "Máquina de costura 1", sector: "Embalagem" },
  { tag: "200", name: "Balança 50kg", sector: "Embalagem" },
  { tag: "201", name: "Balança 1 - 15kg", sector: "Embalagem" },
  { tag: "202", name: "Balança 2 - 15kg", sector: "Embalagem" },
  { tag: "203", name: "Balança 3 - 15kg", sector: "Embalagem" },
  { tag: "204", name: "Balança 4 - 15kg", sector: "Embalagem" },
  { tag: "205", name: "Balança 5 - 15kg", sector: "Embalagem" },
  { tag: "206", name: "Balança 1 - 15kg", sector: "Embalagem" },
  { tag: "207", name: "Balança 2 - 15kg", sector: "Embalagem" },
  { tag: "208", name: "Impressora etiqueta 1", sector: "Embalagem" },
  { tag: "209", name: "Impressora etiqueta 2", sector: "Embalagem" },
  { tag: "210", name: "Impressora etiqueta 3", sector: "Embalagem" },
  { tag: "211", name: "Impressora etiqueta 4", sector: "Embalagem" },
  { tag: "212", name: "Seladora pedal", sector: "Embalagem" },
  { tag: "213", name: "Empilhadeira elétrica", sector: "Expedição" },
  { tag: "214", name: "Paleteira", sector: "Expedição" },
  { tag: "215", name: "Mesa inox 1", sector: "Embalagem" },
  { tag: "216", name: "Mesa inox 2", sector: "Embalagem" },
  { tag: "217", name: "Mesa inox 3", sector: "Embalagem" },
  { tag: "218", name: "Bacia 1", sector: "Embalagem" },
  { tag: "219", name: "Bacia 2", sector: "Embalagem" },
  { tag: "220", name: "Ventilador 1", sector: "Embalagem" },
  { tag: "221", name: "Exaustor", sector: "Embalagem" },
  { tag: "222", name: "Bebedouro", sector: "Embalagem" },
  { tag: "223", name: "Exaustor", sector: "Produção" },
  { tag: "224", name: "Exaustor", sector: "Embalagem" },
  { tag: "225", name: "Exaustor", sector: "Embalagem" },
  { tag: "226", name: "Cortina de ar", sector: "Expedição" },
  { tag: "227", name: "Armadilha luminosa", sector: "Expedição" },
  { tag: "228", name: "TRANSPALETEIRA", sector: "Expedição" },
  { tag: "229", name: "CLIMATIZADOR ECO BRISA", sector: "Expedição" },
  { tag: "230", name: "Ventilador 1", sector: "Expedição" },
  { tag: "231", name: "Ventilador 2", sector: "Expedição" },
  { tag: "232", name: "Armadilha luminosa", sector: "Área Fria" },
  { tag: "233", name: "Relógio ponto", sector: "Área Fria" },
  { tag: "234", name: "Fulão", sector: "Produção" },
  { tag: "235", name: "Motor fulão", sector: "Produção" },
  { tag: "236", name: "Redutor fulão", sector: "Produção" },
  { tag: "237", name: "Painel de controle 1 - Fulão", sector: "Produção" },
  { tag: "238", name: "Painel de controle 2 - Fulão", sector: "Produção" },
  { tag: "239", name: "Enxugadeira", sector: "Produção" },
  { tag: "240", name: "Moedor de couro", sector: "Produção" },
  { tag: "241", name: "Panela de pressão", sector: "Produção" },
  { tag: "242", name: "Máquina de corte 1", sector: "Produção" },
  { tag: "243", name: "Máquina de corte 2", sector: "Produção" },
  { tag: "244", name: "Máquina de corte 3", sector: "Produção" },
  { tag: "245", name: "Balança 50kg", sector: "Produção" },
  { tag: "246", name: "Balança 15kg", sector: "Produção" },
  { tag: "247", name: "Ventilador 1", sector: "Produção" },
  { tag: "248", name: "Ventilador 2", sector: "Produção" },
  { tag: "249", name: "Bebedouro", sector: "Produção" },
  { tag: "250", name: "Moinho", sector: "Moinho" },
  { tag: "251", name: "Motor moinho", sector: "Moinho" },
  { tag: "252", name: "Soprador de ar", sector: "Moinho" },
  { tag: "253", name: "Painel elétrico moinho", sector: "Moinho" },
  { tag: "254", name: "Silo", sector: "Moinho" },
  { tag: "255", name: "Quadro de distribuição energia", sector: "Moinho" },
  { tag: "256", name: "Ventilador 1", sector: "Moinho" },
  { tag: "257", name: "Ventilador 2", sector: "Moinho" },
  { tag: "258", name: "Balança 50kg", sector: "Moinho" },
  { tag: "259", name: "Caldeira", sector: "Caldeira" },
  { tag: "260", name: "Dosadora de Cloro", sector: "Caldeira" },
  { tag: "261", name: "Válvula solenoide 1", sector: "Caldeira" },
  { tag: "262", name: "Válvula solenoide 2", sector: "Caldeira" },
  { tag: "263", name: "Válvula solenoide 3", sector: "Caldeira" },
  { tag: "264", name: "Válvula solenoide 4", sector: "Caldeira" },
  { tag: "265", name: "Válvula solenoide 5", sector: "Caldeira" },
  { tag: "266", name: "Válvula solenoide 6", sector: "Caldeira" },
  { tag: "267", name: "Válvula solenoide 7", sector: "Caldeira" },
  { tag: "268", name: "Válvula solenoide 8", sector: "Caldeira" },
  { tag: "269", name: "Válvula solenoide 9", sector: "Caldeira" },
  { tag: "270", name: "Válvula solenoide 10", sector: "Caldeira" },
  { tag: "271", name: "Exaustor caldeira", sector: "Caldeira" },
  { tag: "272", name: "Motor exaustor", sector: "Caldeira" },
  { tag: "273", name: "Válvula de segurança 8", sector: "Caldeira" },
  { tag: "274", name: "Válvula de segurança 8.4", sector: "Caldeira" },
  { tag: "275", name: "Motobomba", sector: "Caldeira" },
  { tag: "276", name: "Motobomba caldeira", sector: "Caldeira" },
  { tag: "277", name: "Injetor", sector: "Caldeira" },
  { tag: "278", name: "Filtro de entrada de água BIG 20", sector: "Caldeira" },
  { tag: "279", name: "Tanque caldeira", sector: "Caldeira" },
  { tag: "280", name: "Compressor", sector: "Caldeira" },
  { tag: "281", name: "Painel elétrico caldeira", sector: "Caldeira" },
  { tag: "282", name: "Bomba dosadora sulfato de alumínio", sector: "E.T.E" },
  { tag: "283", name: "Bomba dosadora soda", sector: "E.T.E" },
  { tag: "284", name: "Bomba submersiva geral", sector: "E.T.E" },
  { tag: "285", name: "Peneira rotativa", sector: "E.T.E" },
  { tag: "286", name: "Motor peneira", sector: "E.T.E" },
  { tag: "287", name: "Bomba elevação submersa", sector: "E.T.E" },
  { tag: "288", name: "Soprador dos difusores", sector: "E.T.E" },
  { tag: "289", name: "Painel elétrico", sector: "E.T.E" },
  { tag: "290", name: "Painel de distribuição ETE", sector: "E.T.E" },
  { tag: "291", name: "Painel de comando", sector: "E.T.E" },
  { tag: "292", name: "Soprador de ar reator MBBR", sector: "E.T.E" },
  { tag: "293", name: "Painel de comando principal ETE", sector: "E.T.E" },
  { tag: "294", name: "Bomba dosadora polímero", sector: "E.T.E" },
  { tag: "295", name: "Bomba dosadora anti-espumante", sector: "E.T.E" },
  { tag: "296", name: "Motor agitador", sector: "E.T.E" },
  { tag: "297", name: "Redutor agitador", sector: "E.T.E" },
  { tag: "298", name: "Reator MBBR", sector: "E.T.E" },
  { tag: "299", name: "Decantador fisico quimico", sector: "E.T.E" },
  { tag: "300", name: "Caixa da água 10000L", sector: "E.T.E" },
  { tag: "301", name: "Motobomba caixa da água", sector: "E.T.E" },
  { tag: "302", name: "Filtro de areia 1", sector: "E.T.E" },
  { tag: "303", name: "Filtro de areia 2", sector: "E.T.E" },
  { tag: "304", name: "Filtro 1", sector: "E.T.E" },
  { tag: "305", name: "Filtro 2", sector: "E.T.E" },
  { tag: "306", name: "Filtro 3", sector: "E.T.E" },
  { tag: "307", name: "Filtro 4", sector: "E.T.E" },
  { tag: "308", name: "Armário roupeiro 4 portas", sector: "Vestiário" },
  { tag: "309", name: "Armário roupeiro 12 portas", sector: "Vestiário" },
  { tag: "310", name: "Armário roupeiro 1 - 16 portas", sector: "Vestiário" },
  { tag: "311", name: "Armário roupeiro 2 - 16 portas", sector: "Vestiário" },
  { tag: "312", name: "Armário roupeiro 3 - 16 portas", sector: "Vestiário" },
  { tag: "313", name: "Armário roupeiro 4 - 16 portas", sector: "Vestiário" },
  { tag: "314", name: "Armário roupeiro 1 - 8 portas", sector: "Vestiário" },
  { tag: "315", name: "Armário roupeiro 2 - 8 portas", sector: "Vestiário" },
  { tag: "316", name: "Armário roupeiro 3 - 8 portas", sector: "Vestiário" },
  { tag: "317", name: "Armário roupeiro 12 portas", sector: "Vestiário" },
  { tag: "318", name: "Armário roupeiro 1 - 16 portas", sector: "Vestiário" },
  { tag: "319", name: "Armário roupeiro 2 - 16 portas", sector: "Vestiário" },
  { tag: "320", name: "Ventilador 1", sector: "Refeitório" },
  { tag: "321", name: "Ventilador 2", sector: "Refeitório" },
  { tag: "322", name: "Ventilador 3", sector: "Refeitório" },
  { tag: "323", name: "Ventilador 4", sector: "Refeitório" },
  { tag: "324", name: "Ventilador", sector: "Refeitório" },
  { tag: "326", name: "Bebedouro", sector: "Refeitório" },
  { tag: "327", name: "Microondas", sector: "Refeitório" },
  { tag: "328", name: "Fogão", sector: "Refeitório" },
  { tag: "329", name: "Geladeira", sector: "Refeitório" },
  { tag: "330", name: "Tanquinho", sector: "Refeitório" },
  { tag: "331", name: "Ar condicionado", sector: "RH" },
  { tag: "332", name: "Ar condicionado", sector: "Comercial" },
  { tag: "333", name: "Ar condicionado", sector: "Administração" },
  { tag: "334", name: "Frigobar", sector: "Administração" },
  { tag: "335", name: "Bebedouro", sector: "Administração" },
  { tag: "336", name: "TV", sector: "Administração" },
  { tag: "337", name: "Ar condicionado", sector: "Administração" },
  { tag: "338", name: "TV", sector: "Administração" },
  { tag: "339", name: "Ar condicionado", sector: "Administração" },
  { tag: "340", name: "Quadro de distribuição energia", sector: "Manutenção" },
  { tag: "341", name: "Compressor de ar", sector: "Caldeira" },
  { tag: "342", name: "Moldadora de bifinho", sector: "Produção" },
  { tag: "343", name: "Esmeril", sector: "Manutenção" },
  { tag: "344", name: "Serra circular", sector: "Manutenção" },
  { tag: "345", name: "Furadeira de bancada", sector: "Manutenção" },
  { tag: "346", name: "Máquina de solda", sector: "Manutenção" },
  { tag: "347", name: "Parafusadeira furadeira", sector: "Manutenção" },
  { tag: "348", name: "Lixadeira 1 - 115mm", sector: "Manutenção" },
  { tag: "349", name: "Lixadeira 2 - 115mm", sector: "Manutenção" },
  { tag: "350", name: "Lixadeira", sector: "Manutenção" },
  { tag: "351", name: "Martelete", sector: "Manutenção" },
  { tag: "352", name: "Furadeira manual", sector: "Manutenção" },
  { tag: "353", name: "Atomizador/pulverizador", sector: "Manutenção" },
  { tag: "354", name: "Roçadeira", sector: "Manutenção" },
  { tag: "355", name: "Pulverizador manual", sector: "Manutenção" },
  { tag: "356", name: "Soproaspirador", sector: "Manutenção" },
  { tag: "357", name: "Motor elétrico 1 - 7.5 CV", sector: "Manutenção" },
  { tag: "358", name: "Motor elétrico 2 - 7.5 CV", sector: "Manutenção" },
  { tag: "359", name: "Motor elétrico 3 - 7.5 CV", sector: "Manutenção" },
  { tag: "360", name: "Motor elétrico 4", sector: "Manutenção" },
  { tag: "361", name: "Motor elétrico 5", sector: "Manutenção" },
  { tag: "362", name: "Motor elétrico 6", sector: "Manutenção" },
  { tag: "363", name: "Motoredutor - 3 CV", sector: "Manutenção" },
  { tag: "364", name: "Hidrômetro", sector: "Manutenção" },
  { tag: "365", name: "Banco de capacitores", sector: "Manutenção" },
  { tag: "366", name: "Mesa inox 1", sector: "Produção" },
  { tag: "367", name: "Mesa inox 2", sector: "Produção" },
  { tag: "368", name: "Exaustor", sector: "Moinho" },
  { tag: "374", name: "Ventilador 2", sector: "Embalagem" },
  { tag: "375", name: "Ventilador 3", sector: "Embalagem" },
  { tag: "376", name: "Exaustor 1", sector: "Área Fria" },
  { tag: "377", name: "Exaustor 2", sector: "Área Fria" },
  { tag: "378", name: "Exaustor 1", sector: "Sala de Descongelamento" },
  { tag: "379", name: "Exaustor 2", sector: "Sala de Descongelamento" },
  { tag: "380", name: "Exaustor 3", sector: "Sala de Descongelamento" },
  { tag: "381", name: "Exaustor 4", sector: "Sala de Descongelamento" },
  { tag: "382", name: "Exaustor 5", sector: "Sala de Descongelamento" },
  { tag: "383", name: "Exaustor 6", sector: "Sala de Descongelamento" },
  { tag: "384", name: "Computador - Cleiton", sector: "RH" },
  { tag: "385", name: "Servidor", sector: "RH" },
  { tag: "386", name: "Firewall", sector: "RH" },
  { tag: "387", name: "Computador - Adriana", sector: "Comercial" },
  { tag: "388", name: "Notebook - Felipe", sector: "Comercial" },
  { tag: "389", name: "Notebook - Ronaldo", sector: "Comercial" },
  { tag: "390", name: "Notebook - Dalton", sector: "Comercial" },
  { tag: "391", name: "Notebook - Isabela", sector: "Administração" },
  { tag: "392", name: "Notebook - Marcos", sector: "Administração" },
  { tag: "393", name: "Notebook - Mara", sector: "Administração" },
  { tag: "394", name: "Notebook - Larissa", sector: "Administração" },
  { tag: "395", name: "Notebook Karen", sector: "Administração" },
  { tag: "396", name: "Computador - Gabriel", sector: "Administração" },
  { tag: "397", name: "Computador - Karine", sector: "Qualidade, gerência e PCP" },
  { tag: "398", name: "Computador - Claudio/Estufas", sector: "Qualidade, gerência e PCP" },
  { tag: "399", name: "Computador - Alexandre", sector: "Qualidade, gerência e PCP" },
  { tag: "400", name: "Computador - Isabela Maria", sector: "Qualidade, gerência e PCP" },
  { tag: "402", name: "Computador - Sâmela", sector: "Qualidade, gerência e PCP" },
  { tag: "403", name: "Computador - Dara", sector: "Qualidade, gerência e PCP" },
  { tag: "404", name: "Computador - Elaine", sector: "Qualidade, gerência e PCP" },
  { tag: "405", name: "Computador - Linea", sector: "Embalagem" },
  { tag: "406", name: "Computador - Embalagem", sector: "Embalagem" },
  { tag: "407", name: "Computador - Expedição", sector: "Expedição" },
  { tag: "408", name: "Computador - Rafaela", sector: "Extrusão" },
  { tag: "410", name: "Paleteira inox", sector: "Sala de Descongelamento" },
  { tag: "411", name: "Injetora", sector: "Produção" },
  { tag: "412", name: "Paleteira", sector: "Produção" },
  { tag: "413", name: "Empilhadeira elétrica", sector: "Produção" },
  { tag: "414", name: "Seladora automática em L", sector: "Produção" },
  { tag: "415", name: "Clipadeira 1", sector: "Produção" },
  { tag: "416", name: "Serra circular discos", sector: "Produção" },
  { tag: "417", name: "Clipadeira 2", sector: "Produção" },
  { tag: "418", name: "Seladora de blister", sector: "Produção" },
  { tag: "419", name: "Ar condicionado", sector: "Produção" },
  { tag: "420", name: "Bebedouro", sector: "Produção" },
  { tag: "421", name: "Portão eletrônico", sector: "Área Externa" },
  { tag: "422", name: "Mesa", sector: "Extrusão" },
  { tag: "422", name: "Liquidificador industrial", sector: "Área Fria" },
  { tag: "423", name: "Máquina de corte 4", sector: "Produção" },
  { tag: "424", name: "Impressora Tesla", sector: "Embalagem" },
  { tag: "425", name: "Amolador de faca", sector: "Área Fria" },
  { tag: "426", name: "Ventilador", sector: "Produção" },
  { tag: "427", name: "Seladora registron", sector: "Embalagem" },
  { tag: "428", name: "Sala de Descongelamento", sector: "Área Fria" },
  { tag: "478", name: "Predial", sector: "Área Fria" },
  { tag: "9979", name: "Cortina de ar", sector: "Extrusão" },
  { tag: "9980", name: "Estação de Tratamento", sector: "Área Externa" },
  { tag: "9981", name: "INTERFONE", sector: "Área Externa" },
  { tag: "9982", name: "Dosadora de Cloro", sector: "Área Externa" },
  { tag: "9983", name: "Motor elétrico 3", sector: "Estufa" },
  { tag: "9984", name: "Máquina de costura 4", sector: "Embalagem" },
  { tag: "9985", name: "PORTA-COPOS", sector: "Embalagem" },
  { tag: "9986", name: "Tomada", sector: "Produção" },
  { tag: "9987", name: "HIDRAULICA", sector: "Produção" },
  { tag: "9988", name: "ÁREA FRIA", sector: "Área Fria" },
  { tag: "9989", name: "INTERFONE", sector: "Área Externa" },
  { tag: "9990", name: "Painel elétrico extrusora", sector: "Extrusão" },
  { tag: "9991", name: "SETOR SERRA FITA", sector: "Serra" },
  { tag: "9992", name: "Sala PCP", sector: "Área Fria" },
  { tag: "9993", name: "MANGUEIRAS", sector: "Extrusão" },
  { tag: "9994", name: "MANGUEIRAS", sector: "Área Fria" },
  { tag: "9995", name: "LUMINOSO MASTIG", sector: "Produção" },
  { tag: "9996", name: "Lâmpada led tubular", sector: "Produção" },
  { tag: "9997", name: "Lâmpada Bulbo", sector: "Área Fria" },
  { tag: "9998", name: "Biodigestor", sector: "Área Externa" },
  { tag: "99999", name: "Filial Mastig", sector: "Área Externa" },
];
